# Generated by Django 5.0.3 on 2024-06-15 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        ('utility', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('Geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestor.geometry')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('base_metal_alloy', models.CharField(max_length=250)),
                ('alloy', models.CharField(max_length=250)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.quotationstatus')),
            ],
        ),
        migrations.AddField(
            model_name='geometry',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestor.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_condition_value', models.CharField(max_length=250)),
                ('test_object_quantity', models.IntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestor.quotation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.test')),
                ('test_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.condition')),
                ('test_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.testobject')),
                ('unit_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.unitdimension')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_parameter_value', models.CharField(max_length=250)),
                ('quotetion_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestor.quotationdetail')),
                ('test_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.testparameter')),
                ('unit_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.unitdimension')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteionObjectDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_value', models.CharField(max_length=250)),
                ('quotation_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestor.quotationdetail')),
                ('unit_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.unitdimension')),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='requestor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestor.requestor'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('established_date', models.DateField()),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='requestor.requestor')),
            ],
        ),
    ]
