# Generated by Django 5.0.3 on 2024-07-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0002_alter_organization_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='requestor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization', to='requestor.requestor'),
        ),
    ]
