# Generated by Django 5.0.3 on 2024-07-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0005_rename_file_file_file_rename_geometry_file_geometry'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteionObjectDimension',
            new_name='QuotationObjectDimension',
        ),
        migrations.AlterField(
            model_name='file',
            name='geometry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requestor.geometry'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='requestor.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationdetail',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='requestor.quotation'),
        ),
    ]
