# Generated by Django 5.0.3 on 2024-07-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0007_rename_quotetion_detail_quotationtestparameter_quotation_detail'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='utility.quotationstatus'),
        ),
    ]
