# Generated by Django 5.0.2 on 2024-09-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestor', '0008_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationobjectdimension',
            name='quotation_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_dimensions', to='requestor.quotationdetail'),
        ),
        migrations.AlterField(
            model_name='quotationtestparameter',
            name='quotation_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='requestor.quotationdetail'),
        ),
    ]
