# Generated by Django 5.0.3 on 2024-07-02 09:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Test Category', 'verbose_name_plural': 'Test Categories'},
        ),
    ]
